### ISSUE TITLE
Incomplete Implementation of Memory-Based Decision Making and Planning

### ISSUE THREAD

**Issue by Zackary3yin** [mkturkcan/generative-agents#12]
Dear Team,

I'm writing this issue to discuss an aspect of the code related to the behavior, planning, and memory of the agents in the simulation. From my observation of the code, it seems that the agents do not alter their behaviors or plans based on their memories. Furthermore, the decision on which location to visit is not solely based on their plans.

Lack of Memory-based Decision Making: The agents do not seem to make decisions or alter their behaviors based on their memories. An agent's memory of past actions or encounters should influence their future behaviors and decisions. This crucial aspect of memory seems to be missing in the current implementation.

Non-dynamic Planning: The agents' plans do not update based on new memories or encounters. In a realistic scenario, an agent would adapt its plans according to its experiences and memories. However, this doesn't seem to be the case in the current code.

Memory Retrieval: The current memory retrieval only implements the importance aspect from the original text. It lacks the complexity of real-world memory retrieval, which also involves factors like recency, emotional intensity, etc.

I believe addressing these issues could significantly enhance the realism and complexity of the agent's behaviors and interactions in the simulation. Looking forward to your feedback and potential improvements to this aspect of the simulation.

Best Regards,
Zack

**Comment by myrainbowandsky** [comment]
Have you found any more open-source LLM-based generative-agents?

**Comment by mkturkcan** [comment]
The authors of the paper have open-sourced their work at https://github.com/joonspk-research/generative_agents.
