### ISSUE TITLE
IndexError: Replacement index 6 out of range for positional args tuple

### ISSUE THREAD

**Issue by sascham** [mkturkcan/generative-agents#3]
When run the notebook on google colab

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-12-933a493db543>](https://localhost:8080/#) in <cell line: 2>()
      7 
      8   for name in people:
----> 9     prompt = "You are {}. {} You are planning to: {}. You are currently in {} with the following description: {}. It is currently {}:00. The following people are in this area: {}. You can interact with them.".format(name, plans[name], location, town_areas[location], str(global_time), ', '.join(people))
     10     people_description = []
     11     for i in people:

IndexError: Replacement index 6 out of range for positional args tuple

**Comment by robjlyons** [comment]
Hi sascham, if you just remove the second {} after 'You are {}. 

That will fix it. 

Thanks

**Comment by sascham** [comment]
Solved, Thank you
