### ISSUE TITLE
Stops after 40+ min

### ISSUE THREAD

**Issue by sascham** [mkturkcan/generative-agents#4]
No an issue as such, rather more a question.
I looked briefly  over the code but could not see a time limiter or any specific exit criteria. 
But that said, i not went all over it line by line.

Is this by design?

**Comment by robjlyons** [comment]
There is a repeat for loop at the beginning of the final 'Bring it all together' cell:

for repeats in range(5):

It will run through the whole 'Bring it all together' code 5 times and then stop.

Increase this number to make it run looker or change it to while True if you want it to run forever or until you run out of memory.

**Comment by sascham** [comment]
Thanks for the answer, will give it a try
