### ISSUE TITLE
Could not load model declare-lab/flan-alpaca-xl

### ISSUE THREAD

**Issue by sovzzz** [mkturkcan/generative-agents#9]
When run second block, an error occurred (error information attached below). It seems I lack the model. How should I get this model, and where should it be placed?
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [8], in <cell line: 4>()
      1 from transformers import pipeline
      3 prompt = "Write an email about an alpaca that likes flan"
----> 4 model = pipeline(model="declare-lab/flan-alpaca-xl", device=0)
      5 model(prompt, max_length=128, do_sample=True)

File ~/miniconda3/lib/python3.8/site-packages/transformers/pipelines/__init__.py:776, in pipeline(task, model, config, tokenizer, feature_extractor, image_processor, framework, revision, use_fast, use_auth_token, device, device_map, torch_dtype, trust_remote_code, model_kwargs, pipeline_class, **kwargs)
    772 # Infer the framework from the model
    773 # Forced if framework already defined, inferred if it's None
    774 # Will load the correct model if possible
    775 model_classes = {"tf": targeted_task["tf"], "pt": targeted_task["pt"]}
--> 776 framework, model = infer_framework_load_model(
    777     model,
    778     model_classes=model_classes,
    779     config=config,
    780     framework=framework,
    781     task=task,
    782     **hub_kwargs,
    783     **model_kwargs,
    784 )
    786 model_config = model.config
    787 hub_kwargs["_commit_hash"] = model.config._commit_hash

File ~/miniconda3/lib/python3.8/site-packages/transformers/pipelines/base.py:271, in infer_framework_load_model(model, config, model_classes, task, framework, **model_kwargs)
    268             continue
    270     if isinstance(model, str):
--> 271         raise ValueError(f"Could not load model {model} with any of the following classes: {class_tuple}.")
    273 framework = "tf" if "keras.engine.training.Model" in str(inspect.getmro(model.__class__)) else "pt"
    274 return framework, model

ValueError: Could not load model declare-lab/flan-alpaca-xl with any of the following classes: (<class 'transformers.models.auto.modeling_tf_auto.TFAutoModelForSeq2SeqLM'>, <class 'transformers.models.t5.modeling_tf_t5.TFT5ForConditionalGeneration'>).`

**Comment by mkturkcan** [comment]
Let me check if I can reproduce.

**Comment by mkturkcan** [comment]
Cannot reproduce.

**Comment by iPsych** [comment]
@sovzzz Did you properly install Tensorflow but not pytorch in your conda environment?

Above error shows up when you only have TF, since the model is available in torch.
After pip uninstall tensorflow in your conda environment, the pipeline will download the model.
